import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  bool get isChinese => locale.languageCode == 'zh';

  String t(String key, [Map<String, String> values = const {}]) {
    var text =
        (_localizedValues[locale.languageCode] ??
            _localizedValues['en'])![key] ??
        _localizedValues['en']![key] ??
        key;
    values.forEach((name, value) {
      text = text.replaceAll('{$name}', value);
    });
    return text;
  }

  String get calendarLocale => isChinese ? 'zh_CN' : 'en_US';
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'zh'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>> _localizedValues = {
  'en': {
    'app.language': 'Language',
    'app.english': 'English',
    'app.chinese': 'Chinese',
    'app.currentLanguage': 'Current language',
    'app.save': 'Save',
    'app.saving': 'Saving',
    'app.cancel': 'Cancel',
    'app.retry': 'Retry',
    'app.delete': 'Delete',
    'app.report': 'Report',
    'app.block': 'Block',
    'auth.login': 'Log in',
    'auth.confirm': 'Confirm',
    'auth.register': 'Sign up',
    'auth.emailLabel': 'Email',
    'auth.emailHint': 'Enter email address',
    'auth.accountRequired': 'Please enter email or phone number',
    'auth.phoneLabel': 'Please enter your phone number',
    'auth.phoneNumberLabel': 'Phone number',
    'auth.phoneHint': '13212345678',
    'auth.phoneRequired': 'Please enter your phone number',
    'auth.passwordLabel': 'Password',
    'auth.passwordPrompt': 'Please enter your password',
    'auth.passwordHint': 'Your password',
    'auth.passwordRequired': 'Please enter password',
    'auth.agreementPrefix': 'Logging in means you agree to the user ',
    'auth.serviceAgreement': 'service agreement',
    'auth.agreementMiddle': ' and ',
    'auth.privacyPolicy': 'private policy',
    'auth.agreementRequired':
        'Please agree to the service agreement and privacy policy',
    'auth.countryCode': 'Country code',
    'auth.registerEmailLabel': 'Registration email',
    'auth.confirmPasswordLabel': 'Confirm password',
    'auth.confirmPasswordHint': 'Enter password again',
    'auth.loginFailed': 'Login failed',
    'auth.loginException': 'Login error: {error}',
    'auth.checkingUser': 'Checking account status...',
    'auth.userExists': 'Account found. Continue with password.',
    'auth.userNotFound': 'New phone number. Sign up required.',
    'auth.userCheckFailed': 'Failed to check account status',
    'auth.registerRequired':
        'This phone number is not registered. Continue to sign up.',
    'auth.sendSms': 'Send code',
    'auth.verifySms': 'Verify code',
    'auth.completeRegister': 'Complete',
    'auth.smsCode': 'SMS code',
    'auth.smsCodeHint': 'Enter SMS code',
    'auth.smsSent': 'Verification code sent',
    'auth.smsRequired': 'Please enter SMS code',
    'auth.resendIn': '{seconds}s',
    'auth.passwordLength': 'Password must be 6-20 characters',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.registerSuccess': 'Sign up successful',
    'auth.registerFailed': 'Sign up failed',
    'auth.countryCodeLoadFailed': 'Failed to load country code',
    'home.captureDescription': 'A mood was captured today.',
    'home.captureTitle': 'You caught a good mood today',
    'home.open': 'Open',
    'home.friendsActivity': 'Friends Activity',
    'home.all': 'All',
    'home.hot': 'Hot',
    'home.feedLoadFailed': 'Failed to load rooms',
    'home.roomsEmpty': 'No rooms yet',
    'party.tabParty': 'Party',
    'party.tabRoom': 'Room',
    'party.now': 'Now',
    'party.new': 'New',
    'party.join': 'Join',
    'party.onLive': 'On Live',
    'party.loadFailed': 'Failed to load parties',
    'party.noData': 'No parties yet',
    'party.untitled': 'Tittle-Happy Day',
    'party.username': 'Username',
    'createParty.title': 'Create party',
    'createParty.coverPicture': 'Cover picture',
    'createParty.coverRequirement': 'Format:jpg,png  Size:650*244',
    'createParty.topic': 'Topic',
    'createParty.topicHint': 'Please enter your event topic',
    'createParty.description': 'Description',
    'createParty.descriptionHint': 'Say some details about your event',
    'createParty.time': 'Time',
    'createParty.startTime': 'Start time:',
    'createParty.duration': 'Duration:',
    'createParty.tag': 'Tag',
    'createParty.tagHint': 'Choose tags to attract users',
    'createParty.chooseTags': 'Choose tags',
    'createParty.confirm': 'Confirm',
    'createParty.uploadingCover': 'Uploading cover...',
    'createParty.submitting': 'Creating...',
    'createParty.coverRequired': 'Please upload a cover picture',
    'createParty.topicRequired': 'Please enter your event topic',
    'createParty.descriptionRequired': 'Please enter event description',
    'createParty.createSuccess': 'Party created',
    'createParty.tagsLoadFailed': 'Failed to load tags',
    'createParty.timeSheetTitle': 'Select start time',
    'createRoom.title': 'Create room',
    'createRoom.avatarTooltip': 'Change room avatar',
    'createRoom.name': 'Room Name',
    'createRoom.nameHint': "Let's go Party!",
    'createRoom.description': 'Room Description',
    'createRoom.descriptionHint': 'Please enter here',
    'createRoom.confirm': 'Comfirm',
    'createRoom.submitting': 'Creating...',
    'createRoom.avatarRequired': 'Please upload a room avatar',
    'createRoom.titleRequired': 'Please enter room name',
    'createRoom.descriptionRequired': 'Please enter room description',
    'createRoom.fetchOwnRoomFailed': 'Failed to get room info',
    'createRoom.createFailed': 'Failed to create room',
    'createRoom.enterFailed': 'Failed to enter room',
    'createRoom.createSuccess': 'Room created',
    'rank.title': 'Ranking',
    'rank.wealth': 'Wealth',
    'rank.charm': 'Charm',
    'rank.room': 'Room',
    'rank.daily': 'Daily',
    'rank.weekly': 'Weekly',
    'rank.total': 'Total',
    'rank.day': 'day',
    'rank.hour': 'hour',
    'rank.min': 'min',
    'rank.sec': 'sec',
    'rank.help': 'Ranking rules',
    'rank.loadFailed': 'Failed to load ranking',
    'rank.empty': 'No ranking data yet',
    'calendar.noMoodRecords': 'No mood records',
    'calendar.onlyToday': 'You can only post today\'s mood.',
    'publish.selectMood': 'Select mood',
    'publish.writeMood': 'Write mood',
    'publish.moodHint': 'What happened today...',
    'publish.saveSuccess': 'Saved',
    'publish.needContent': 'Enter content or choose an image',
    'publish.needVoice': 'Please record audio',
    'publish.maxImages': 'You can choose up to 4 images',
    'publish.maxImagesAdded': 'You can choose up to 4 images. Added {count}.',
    'publish.noRecordPermission': 'Microphone permission denied',
    'publish.startRecording': 'Tap to start recording',
    'publish.stopRecording': 'Tap to stop recording',
    'content.todayMood': 'This is my mood today',
    'message.title': 'Messages',
    'message.empty': 'No messages',
    'message.me': 'Me',
    'message.contact': 'Contact',
    'message.yesterday': 'Yesterday',
    'message.dialogTitle': 'Notice',
    'message.deleteConversation': 'Delete conversation',
    'message.loadFailed': 'Failed to load messages',
    'message.emptyPreview': 'No message content',
    'chat.title': 'Chat',
    'chat.inputHint': 'Say something...',
    'chat.targetMissing': 'Missing chat target',
    'profile.username': 'Username',
    'profile.nickname': 'User nickname',
    'profile.myPosts': 'My Posts',
    'profile.blockList': 'Block List',
    'profile.privacy': 'Privacy',
    'profile.aboutUs': 'About us',
    'profile.contactUs': 'Contact Us',
    'profile.settings': 'Settings',
    'profile.deleteAccount': 'Delete Account',
    'profile.logOut': 'Log Out',
    'profile.wallet': 'Wallet',
    'profile.recharge': 'Recharge',
    'profile.inviteFriends': 'Invite friends',
    'profile.store': 'Store',
    'profile.level': 'Level',
    'profile.backpack': 'Backpack',
    'profile.following': 'Following',
    'profile.followers': 'Followers',
    'profile.visitors': 'Visitors',
    'profile.follow': 'Follow',
    'profile.followingStatus': 'Following',
    'profile.relationsEmpty': 'No users yet',
    'profile.relationsLoadFailed': 'Failed to load users',
    'profile.vip': 'VIP',
    'profile.noble': 'Noble',
    'profile.wealth': 'Wealth',
    'profile.charm': 'Charm',
    'profile.room': 'Room',
    'profile.guard': 'Guard',
    'profile.badge': 'Badge',
    'profile.honor': 'Honor',
    'profile.achieved': '{count} achieved',
    'profile.myBadge': 'My Badge>',
    'profile.honorEmpty': 'No honors yet',
    'profile.myTeam': 'My team',
    'profile.agent': 'Agent',
    'profile.bd': 'BD',
    'profile.host': 'Host',
    'profile.manage': 'Manage',
    'profile.dailyReward': 'Daily\nReward',
    'profile.saleCoin': 'Sale\nCoin',
    'profile.gameCoin': 'Game\nCoin',
    'profile.editProfile': 'Edit profile',
    'profile.avatar': 'Avatar',
    'profile.gender': 'Gender',
    'profile.birthday': 'Birthday',
    'profile.chooseGender': 'Choose gender',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.saved': 'Saved',
    'profile.loadFailed': 'Failed to load profile',
    'profile.countryRegion': 'Country / Region',
    'profile.phone': 'Phone',
    'profile.userId': 'User ID',
    'profile.bio': 'Bio',
    'profile.bioHint': 'Enter bio',
    'profile.notSet': 'Not set',
    'profile.avatarUploaded': 'Avatar uploaded',
    'profile.avatarUploadFailed': 'Avatar upload failed',
    'profile.selectedMale': 'Male selected',
    'profile.selectedFemale': 'Female selected',
    'profile.editNickname': 'Edit nickname',
    'profile.nicknameHint': 'Enter nickname',
    'profile.nicknameSaved': 'Nickname saved: {nickname}',
    'profile.nicknameRequired': 'Nickname cannot be empty',
    'profile.nicknameTooLong': 'Nickname cannot exceed 20 characters',
    'profile.nicknameRule': 'Nickname length: 1-20 characters',
    'profile.noPosts': 'No posts',
    'profile.postsLoadFailed': 'Failed to load posts',
    'profile.homepage': 'Profile',
    'profile.homepageEmpty': 'No profile data',
    'profile.homepageLoadFailed': 'Failed to load profile',
    'profile.about': 'About',
    'profile.album': 'Album',
    'profile.noPhotos': 'No photos yet',
    'profile.bioEmpty': 'No bio yet',
    'profile.giftValue': 'Collected',
    'profile.giftsReceived': '{count} gifts received',
    'profile.gifts': 'Gifts',
    'profile.joined': 'Joined:',
    'profile.days': '{days} Days',
    'profile.chat': 'Chat',
    'profile.comingSoon': 'Coming soon',
    'profile.logOutMessage': 'Are you sure you want to log out?',
    'profile.deleteAccountMessage':
        'Deleting your account is permanent. Are you sure you want to continue?',
    'profile.deleteAccountFailed': 'Failed to delete account',
    'profile.logoutFailed': 'Logout failed',
    'settings.userAgreement': 'User Agreement',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.termsOfUse': 'Terms of use',
    'settings.empty': 'No more settings',
    'about.version': 'Version 1.0.0',
    'about.description':
        'Record your daily emotions and moments, and keep your moods safe.',
    'detail.moodDetail': 'Mood detail',
    'picker.album': 'Choose from album',
    'picker.camera': 'Take photo',
    'picker.albumSelected': 'Album selected',
    'picker.cameraSelected': 'Camera selected',
  },
  'zh': {
    'app.language': '语言',
    'app.english': '英文',
    'app.chinese': '中文',
    'app.currentLanguage': '当前语言',
    'app.save': '保存',
    'app.saving': '保存中',
    'app.cancel': '取消',
    'app.retry': '重试',
    'app.delete': '删除',
    'app.report': '举报',
    'app.block': '拉黑',
    'auth.login': '登录',
    'auth.confirm': '确认',
    'auth.register': '注册',
    'auth.emailLabel': '请输入邮箱',
    'auth.emailHint': '请输入邮箱地址',
    'auth.accountRequired': '请输入邮箱或手机号',
    'auth.phoneLabel': '请输入手机号',
    'auth.phoneNumberLabel': '手机号',
    'auth.phoneHint': '13212345678',
    'auth.phoneRequired': '请输入手机号',
    'auth.passwordLabel': '请输入密码',
    'auth.passwordPrompt': '请输入密码',
    'auth.passwordHint': '请输入密码',
    'auth.passwordRequired': '请输入密码',
    'auth.agreementPrefix': '登录即表示你同意用户',
    'auth.serviceAgreement': '服务协议',
    'auth.agreementMiddle': '和',
    'auth.privacyPolicy': '隐私政策',
    'auth.agreementRequired': '请先同意服务协议和隐私政策',
    'auth.countryCode': '国家码',
    'auth.registerEmailLabel': '请输入注册邮箱',
    'auth.confirmPasswordLabel': '请再次输入密码',
    'auth.confirmPasswordHint': '请再次输入密码',
    'auth.loginFailed': '登录失败',
    'auth.loginException': '登录异常：{error}',
    'auth.checkingUser': '正在检查账号状态...',
    'auth.userExists': '账号已存在，请继续输入密码',
    'auth.userNotFound': '该手机号未注册，请继续注册',
    'auth.userCheckFailed': '账号状态检查失败',
    'auth.registerRequired': '该手机号尚未注册，请继续完成注册',
    'auth.sendSms': '发送验证码',
    'auth.verifySms': '校验验证码',
    'auth.completeRegister': '完成注册',
    'auth.smsCode': '短信验证码',
    'auth.smsCodeHint': '请输入短信验证码',
    'auth.smsSent': '验证码已发送',
    'auth.smsRequired': '请输入短信验证码',
    'auth.resendIn': '{seconds}s',
    'auth.passwordLength': '密码长度需为6-20位',
    'auth.passwordMismatch': '两次输入的密码不一致',
    'auth.registerSuccess': '注册成功',
    'auth.registerFailed': '注册失败',
    'auth.countryCodeLoadFailed': '国家码获取失败',
    'home.captureDescription': '这是今天捕捞到的一条心情。',
    'home.captureTitle': '今天也捕捞到一颗好心情',
    'home.open': '打开',
    'home.friendsActivity': '好友动态',
    'home.all': '全部',
    'home.hot': '热门',
    'home.feedLoadFailed': '房间加载失败',
    'home.roomsEmpty': '暂无房间',
    'party.tabParty': '派对',
    'party.tabRoom': '房间',
    'party.now': '当前',
    'party.new': '最新',
    'party.join': '加入',
    'party.onLive': '直播中',
    'party.loadFailed': '派对加载失败',
    'party.noData': '暂无派对',
    'party.untitled': '快乐派对',
    'party.username': '用户名',
    'createParty.title': 'Create party',
    'createParty.coverPicture': '封面图',
    'createParty.coverRequirement': '格式:jpg,png  尺寸:650*244',
    'createParty.topic': '主题',
    'createParty.topicHint': '请输入活动主题',
    'createParty.description': '描述',
    'createParty.descriptionHint': '说说活动详情',
    'createParty.time': '时间',
    'createParty.startTime': '开始时间:',
    'createParty.duration': '时长:',
    'createParty.tag': '标签',
    'createParty.tagHint': '选择标签吸引用户',
    'createParty.chooseTags': '选择标签',
    'createParty.confirm': '确认',
    'createParty.uploadingCover': '封面上传中...',
    'createParty.submitting': '创建中...',
    'createParty.coverRequired': '请上传封面图',
    'createParty.topicRequired': '请输入活动主题',
    'createParty.descriptionRequired': '请输入活动描述',
    'createParty.createSuccess': '派对创建成功',
    'createParty.tagsLoadFailed': '标签加载失败',
    'createParty.timeSheetTitle': '选择开始时间',
    'createRoom.title': 'Create room',
    'createRoom.avatarTooltip': '更换房间头像',
    'createRoom.name': '房间名称',
    'createRoom.nameHint': "Let's go Party!",
    'createRoom.description': '房间介绍',
    'createRoom.descriptionHint': '请输入房间介绍',
    'createRoom.confirm': '确认',
    'createRoom.submitting': '创建中...',
    'createRoom.avatarRequired': '请上传房间头像',
    'createRoom.titleRequired': '请输入房间名称',
    'createRoom.descriptionRequired': '请输入房间介绍',
    'createRoom.fetchOwnRoomFailed': '获取房间信息失败',
    'createRoom.createFailed': '创建房间失败',
    'createRoom.enterFailed': '进入房间失败',
    'createRoom.createSuccess': '房间创建成功',
    'rank.title': '排行榜',
    'rank.wealth': '财富',
    'rank.charm': '魅力',
    'rank.room': '房间',
    'rank.daily': '日榜',
    'rank.weekly': '周榜',
    'rank.total': '总榜',
    'rank.day': '天',
    'rank.hour': '时',
    'rank.min': '分',
    'rank.sec': '秒',
    'rank.help': '榜单规则',
    'rank.loadFailed': '排行榜加载失败',
    'rank.empty': '暂无榜单数据',
    'calendar.noMoodRecords': '暂无心情记录',
    'calendar.onlyToday': '只能在当天发布心情哦~',
    'publish.selectMood': '选择心情',
    'publish.writeMood': '填写心情',
    'publish.moodHint': '今天发生了什么...',
    'publish.saveSuccess': '保存成功！',
    'publish.needContent': '请输入内容或选择图片',
    'publish.needVoice': '请录制语音',
    'publish.maxImages': '最多只能选择4张图片',
    'publish.maxImagesAdded': '最多只能选择4张图片，已添加{count}张',
    'publish.noRecordPermission': '没有录音权限',
    'publish.startRecording': '点击开始录音',
    'publish.stopRecording': '点击停止录音',
    'content.todayMood': '这是我今天的心情',
    'message.title': '消息',
    'message.empty': '暂无消息',
    'message.me': '我',
    'message.contact': '联系人',
    'message.yesterday': '昨天',
    'message.dialogTitle': '提示',
    'message.deleteConversation': '删除对话',
    'message.loadFailed': '消息加载失败',
    'message.emptyPreview': '暂无消息内容',
    'chat.title': '聊天',
    'chat.inputHint': '说点什么...',
    'chat.targetMissing': '缺少聊天对象',
    'profile.username': '用户名',
    'profile.nickname': '用户昵称',
    'profile.myPosts': '我的帖子',
    'profile.blockList': '黑名单',
    'profile.privacy': '用户隐私',
    'profile.aboutUs': '关于我们',
    'profile.contactUs': '联系我们',
    'profile.settings': '设置',
    'profile.deleteAccount': '删除账号',
    'profile.logOut': '退出登录',
    'profile.wallet': '钱包',
    'profile.recharge': '充值',
    'profile.inviteFriends': '邀请好友',
    'profile.store': '商城',
    'profile.level': '等级',
    'profile.backpack': '背包',
    'profile.following': '关注',
    'profile.followers': '粉丝',
    'profile.visitors': '访客',
    'profile.follow': '关注',
    'profile.followingStatus': '已关注',
    'profile.relationsEmpty': '暂无用户',
    'profile.relationsLoadFailed': '用户列表加载失败',
    'profile.vip': 'VIP',
    'profile.noble': '贵族',
    'profile.wealth': '财富',
    'profile.charm': '魅力',
    'profile.room': '房间',
    'profile.guard': '守护',
    'profile.badge': '徽章',
    'profile.honor': '荣誉',
    'profile.achieved': '已获得 {count} 个',
    'profile.myBadge': '我的徽章>',
    'profile.honorEmpty': '暂无荣誉',
    'profile.myTeam': '我的团队',
    'profile.agent': '代理',
    'profile.bd': 'BD',
    'profile.host': '主播',
    'profile.manage': '管理',
    'profile.dailyReward': '每日奖励',
    'profile.saleCoin': '售币',
    'profile.gameCoin': '游戏币',
    'profile.editProfile': '编辑资料',
    'profile.avatar': '头像',
    'profile.gender': '性别',
    'profile.birthday': '生日',
    'profile.chooseGender': '选择性别',
    'profile.male': '男',
    'profile.female': '女',
    'profile.saved': '保存成功',
    'profile.loadFailed': '资料加载失败',
    'profile.countryRegion': '国家/地区',
    'profile.phone': '手机号',
    'profile.userId': '用户ID',
    'profile.bio': '个人简介',
    'profile.bioHint': '请输入个人简介',
    'profile.notSet': '未设置',
    'profile.avatarUploaded': '头像已上传',
    'profile.avatarUploadFailed': '头像上传失败',
    'profile.selectedMale': '已选择男',
    'profile.selectedFemale': '已选择女',
    'profile.editNickname': '编辑昵称',
    'profile.nicknameHint': '请输入昵称',
    'profile.nicknameSaved': '昵称已保存：{nickname}',
    'profile.nicknameRequired': '昵称不能为空',
    'profile.nicknameTooLong': '昵称不能超过20个字符',
    'profile.nicknameRule': '昵称长度为1-20个字符',
    'profile.noPosts': '暂无帖子',
    'profile.postsLoadFailed': '帖子加载失败',
    'profile.homepage': '个人主页',
    'profile.homepageEmpty': '暂无主页数据',
    'profile.homepageLoadFailed': '个人主页加载失败',
    'profile.about': '关于',
    'profile.album': '相册',
    'profile.noPhotos': '暂无照片',
    'profile.bioEmpty': '这个人还没有留下简介',
    'profile.giftValue': '已收集',
    'profile.giftsReceived': '已收到 {count} 个礼物',
    'profile.gifts': '礼物',
    'profile.joined': '加入:',
    'profile.days': '{days} 天',
    'profile.chat': '聊天',
    'profile.comingSoon': '功能待接入',
    'profile.logOutMessage': '确定要退出登录吗？',
    'profile.deleteAccountMessage': '删除账号后将无法恢复，确定继续吗？',
    'profile.deleteAccountFailed': '删除账号失败',
    'profile.logoutFailed': '退出登录失败',
    'settings.userAgreement': '用户协议',
    'settings.privacyPolicy': '隐私政策',
    'settings.termsOfUse': '使用条款',
    'settings.empty': '暂无更多设置',
    'about.version': '版本 1.0.0',
    'about.description': '记录每天的情绪和片刻，把心情好好收藏起来。',
    'detail.moodDetail': '心情详情',
    'picker.album': '从相册选择',
    'picker.camera': '拍照',
    'picker.albumSelected': '已选择相册',
    'picker.cameraSelected': '已选择拍照',
  },
};
